inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics:
   Enabled: true

Layout/LineLength:
  Max: 80
